### ISSUE TITLE
undefined method `effective_form_with' for #<#<Class:0x00005569d5f0a430>:0x00005569d5ef53c8>

### ISSUE THREAD

**Issue by victormaths** [code-and-effect/effective_datatables#123]
/home/orochi/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/effective_datatables-92e5f7aceb09/app/helpers/effective_datatables_private_helper.rb:81:in `datatable_search_tag'
/home/orochi/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/effective_datatables-92e5f7aceb09/app/helpers/effective_datatables_private_helper.rb:14:in `block in datatable_columns'
/home/orochi/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/effective_datatables-92e5f7aceb09/app/helpers/effective_datatables_private_helper.rb:8:in `each'
/home/orochi/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/effective_datatables-92e5f7aceb09/app/helpers/effective_datatables_private_helper.rb:8:in `map'
/home/orochi/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/effective_datatables-92e5f7aceb09/app/helpers/effective_datatables_private_helper.rb:8:in `datatable_columns'
/home/orochi/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/effective_datatables-92e5f7aceb09/app/helpers/effective_datatables_helper.rb:46:in `render_datatable'
app/views/admins/poker_clubs/show.html.erb:2:in `_app_views_admins_poker_clubs_show_html_erb__532051375007255396_46956524625000'

My players_datatable.rb file:

`class PlayersDatatable < Effective::Datatable
  datatable do
    col :name
  end

  collection do
    Player.all
  end
end
`

Im using Rails 5.2.1 w/ ruby 2.5.7

**Comment by victormaths** [comment]
Just included EffectiveFormBuilderHelper on my ApplicationHelper.

module ApplicationHelper
    include EffectiveFormBuilderHelper
