### ISSUE TITLE
Puma caught this error: uninitialized constant Effective::FlashMessages (NameError)

### ISSUE THREAD

**Issue by navidkhn1** [code-and-effect/effective_datatables#124]
Hey, 

This error is coming up when running `rails server` - 

```
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/effective_resources-1.3.16/lib/effective_resources/engine.rb:54:in `block (2 levels) in <class:Engine>'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_controller/api.rb:148:in `<class:API>'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_controller/api.rb:89:in `<module:ActionController>'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_controller/api.rb:7:in `<main>'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/zeitwerk-2.2.0/lib/zeitwerk/kernel.rb:23:in `require'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/jbuilder-2.9.1/lib/jbuilder/railtie.rb:20:in `block (2 levels) in <class:Railtie>'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_controller/base.rb:269:in `<class:Base>'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_controller/base.rb:166:in `<module:ActionController>'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_controller/base.rb:7:in `<main>'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/zeitwerk-2.2.0/lib/zeitwerk/kernel.rb:23:in `require'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_dispatch/middleware/static.rb:78:in `ext'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_dispatch/middleware/static.rb:35:in `match?'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_dispatch/middleware/static.rb:120:in `call'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/actionpack-6.0.0/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/webpacker-4.0.7/lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0/lib/rails/engine.rb:526:in `call'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/Users/navedkhan/.rvm/gems/ruby-2.6.3/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

which eventually causes problems with `gem 'devise'`. I am on `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]` and `Rails 6.0.0`.

This is the relevant section of my Gemfile:
```
# data tables
gem 'hamlit-rails'
gem 'effective_bootstrap'
gem 'effective_resources'
gem 'effective_datatables'
```

and my config: 
```
EffectiveDatatables.setup do |config|
  # Authorization Method
  #
  # This method is called by all controller actions with the appropriate action and resource
  # If it raises an exception or returns false, an Effective::AccessDenied Error will be raised
  #
  # Use via Proc:
  # Proc.new { |controller, action, resource| authorize!(action, resource) }       # CanCan
  # Proc.new { |controller, action, resource| can?(action, resource) }             # CanCan with skip_authorization_check
  # Proc.new { |controller, action, resource| authorize "#{action}?", resource }   # Pundit
  # Proc.new { |controller, action, resource| current_user.is?(:admin) }           # Custom logic
  #
  # Use via Boolean:
  # config.authorization_method = true  # Always authorized
  # config.authorization_method = false # Always unauthorized
  #
  # Use via Method (probably in your application_controller.rb):
  config.authorization_method = :my_authorization_method
  def my_authorization_method(resource, action)
    true
  end
  # config.authorization_method = Proc.new { |controller, action, resource| authorize!(action, resource) }

  # Default number of entries shown per page
  # Valid options are: 5, 10, 25, 50, 100, 250, 500, :all
  config.default_length = 25

  # Default class used on the <table> tag
  config.html_class = 'table table-hover'

  # Log search/sort information to the console
  config.debug = true

  # Use a cookie to save and restore state from previous page visits.
  config.save_state = true

  # Configure the _effective_dt cookie.
  config.cookie_max_size = 2000       # String size. Final byte size is about 1.5 times bigger, after rails signs it
  config.cookie_domain = :all         # Should usually be :all
  config.cookie_tld_length = nil      # Leave nil to autodetect, or set to probably 2

end

```

Every thing is pretty much default, can't seem to pin point the problem. Can you please help? :)

**Comment by matt-riemer** [comment]
Think this is a rails6 bug...zeitwerk...

Will dig into this tomorrow, cheers :)

**Comment by matt-riemer** [comment]
Hey

Please upgrade to `effective_resources 1.4.0` for the fix to this issue!

And please do open another github Issue for any Rails 6/zeitwerk issues you run into with this or any other effective gem. You rock!

I think I just squashed all the zeitwerk bugs, although there could be another bug or two in there somewhere...

**Comment by navidkhn1** [comment]
Will do, thank you! 😄
