### ISSUE TITLE
Minimum ruby version is probably worth mentioning

### ISSUE THREAD

**Issue by nfedyashev** [code-and-effect/effective_datatables#127]
Unfortunately I'm stuck with using an older version of effective_datatables at the moment. Latest stable one with Rails4 compatibility which is `3.7.3`.

Since this is a legacy app, I decided to clone the production environment(Heroku) so I was running Ruby `2.2.6`.

Turns out effective_datatables doesn't seem to work with ruby versions prior to 2.3.0 - that's when "Safe Navigation Operator" was introduced. `effective_resources` gem relies on it.

Stacktrace:
```
rails_1     | => Booting WEBrick
rails_1     | => Rails 4.2.1 application starting in development on http://0.0.0.0:4000
rails_1     | => Run `rails server -h` for more startup options
rails_1     | => Ctrl-C to shutdown server
rails_1     | Exiting
rails_1     | /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load': /bundle/gems/effective_resources-1.4.1/app/models/concerns/acts_as_statused.rb:116: syntax error, unexpected '.' (SyntaxError)
rails_1     |       self.status_steps["#{status}_by".to_sym] ||= current_user&.id
rails_1     |                                                                  ^
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:526:in `load_missing_constant'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:526:in `load_missing_constant'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
rails_1     | 	from /bundle/gems/effective_resources-1.4.1/lib/effective_resources/engine.rb:23:in `block (2 levels) in <class:Engine>'
rails_1     | 	from /bundle/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
```

**Comment by matt-riemer** [comment]
Heyo @nfedyashev 

I too support a whole bunch of rails 3, rails 4 apps that need support for the older rubys.  I just haven't upgraded effective_datatables or effective_resources on them in forevers :)

So um, I have gone and changed the `&.` to `.try()` in both effective_resources and effective_datatables gems.

I'm not 100% guaranteeing that these will work -- there might be other ruby issues --

But give it a shot:

effective_datatables 3.7.5  (bootstrap3)
effective_resources 1.4.2

**Comment by nfedyashev** [comment]
Hi @matt-riemer 

thanks for the tip.

Unfortunately, I can't verify those versions. It was urgent so I upgraded to newer versions of Rails&effective_datatables instead.
