### ISSUE TITLE
Rails 7

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#167]
Hi,

I am trying to update to Rails 7 and I got an error with Effective Datatables.

````
➜  coku-app git:(master) ✗  rspec spec/interactors/company/create_spec.rb

An error occurred while loading rails_helper.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NameError:
  uninitialized constant EffectiveDatatables::Engine::EffectiveDatatablesHelper
# /Users/Nerian/projects/effective_datatables/lib/effective_datatables/engine.rb:10:in `block (2 levels) in <class:Engine>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/actionpack-7.0.0/lib/action_controller/base.rb:270:in `<class:Base>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/actionpack-7.0.0/lib/action_controller/base.rb:166:in `<module:ActionController>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/actionpack-7.0.0/lib/action_controller/base.rb:7:in `<top (required)>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/zeitwerk-2.5.2/lib/zeitwerk/kernel.rb:36:in `require'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/actionpack-7.0.0/lib/action_controller/railtie.rb:81:in `block (3 levels) in <class:Railtie>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/actionpack-7.0.0/lib/action_controller/railtie.rb:77:in `each'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/actionpack-7.0.0/lib/action_controller/railtie.rb:77:in `block (2 levels) in <class:Railtie>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/actionpack-7.0.0/lib/action_controller/api.rb:148:in `<class:API>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/actionpack-7.0.0/lib/action_controller/api.rb:89:in `<module:ActionController>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/actionpack-7.0.0/lib/action_controller/api.rb:7:in `<top (required)>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/zeitwerk-2.5.2/lib/zeitwerk/kernel.rb:36:in `require'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/sorcery-0.16.2/lib/sorcery/engine.rb:16:in `block in <class:Engine>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `instance_exec'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `run'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/initializable.rb:60:in `run_initializers'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/application.rb:369:in `initialize!'
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:9:in `require'
# ./spec/rails_helper.rb:9:in `<top (required)>'
````

This originates from here:
https://github.com/code-and-effect/effective_datatables/blob/master/lib/effective_datatables/engine.rb#L10

Looks like Zeitwerk is not able to find the helper.

I tried commenting the code for both initializers in that file just to see what else happens, and it got a similar error for EffectiveResources:

```
➜  coku-app git:(master) ✗  rspec spec/interactors/company/create_spec.rb

An error occurred while loading rails_helper.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

NameError:
  uninitialized constant EffectiveResources::Engine::ActsAsArchived
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/effective_resources-1.9.12/lib/effective_resources/engine.rb:25:in `block (2 levels) in <class:Engine>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:42:in `each'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/activesupport-7.0.0/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/effective_resources-1.9.12/lib/effective_resources/engine.rb:24:in `block in <class:Engine>'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `instance_exec'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `run'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/initializable.rb:60:in `run_initializers'
# /Users/Nerian/.rvm/gems/ruby-2.7.5/gems/railties-7.0.0/lib/rails/application.rb:369:in `initialize!'
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:9:in `require'
# ./spec/rails_helper.rb:9:in `<top (required)>'
```

Looks like the gems are not following zeitwerk naming conventions. It is strange that it just began failing in Rails 7, since I have zeitwerk activated in Rails 6 too 🤔  Any ideas?

**Comment by danajanssen** [comment]
Not speaking for @matt-riemer but imo we won't be exploring support for Rails 7 in effective_datatables until after 7.1 is released. This is because we typically follow a major version behind latest Rails. This *might* get looked at when we do an upgrade to Bootstrap 5, which is hopefully in Q1 2022, but that work isn't locked in our schedule yet.

**Comment by matt-riemer** [comment]
effective_datatables and effective_resources, a dependency, are both working on Rails 7 now!

**Comment by Nerian** [comment]
Nice, thanks! I am having some issues updating though. It seems like effective_datatable and the sorcery gem does not play nice together in Rails 7. Pretty weird. I also get the same errors with effective_resources and effective_bootstrap. 

Steps to reproduce:
On a clean new Rails 7 app, add effective_datatable and sorcery gem. Bundle install. try to launch console. I get:

```
➜  app_test git:(main) ✗  rails c
/Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/Nerian/.rvm/gems/ruby-2.7.4/gems/net-protocol-0.1.2/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/Users/Nerian/.rvm/gems/ruby-2.7.4/gems/net-protocol-0.1.2/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/Users/Nerian/.rvm/gems/ruby-2.7.4/gems/net-protocol-0.1.2/lib/net/protocol.rb:504: warning: previous definition of Socket was here
Traceback (most recent call last):
	39: from bin/rails:4:in `<main>'
	38: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	37: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	36: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
	35: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
	34: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
	33: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	32: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	31: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	30: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:101:in `perform'
	29: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	28: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/command/actions.rb:28:in `require_environment!'
	27: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/application.rb:348:in `require_environment!'
	26: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	25: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	24: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	23: from /private/tmp/app_test/config/environment.rb:5:in `<main>'
	22: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
	21: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
	20: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	19: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	18: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	17: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:347:in `call'
	16: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:347:in `each'
	15: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	14: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	13: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	12: from /Users/Nerian/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	11: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	10: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
	 9: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
	 8: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/effective_resources-1.17.0/lib/effective_resources/engine.rb:24:in `block in <class:Engine>'
	 7: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
	 6: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:42:in `each'
	 5: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
	 4: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	 3: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	 2: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	 1: from /Users/Nerian/.rvm/gems/ruby-2.7.4/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/Users/Nerian/.rvm/gems/ruby-2.7.4/gems/effective_resources-1.17.0/lib/effective_resources/engine.rb:25:in `block (2 levels) in <class:Engine>': uninitialized constant EffectiveResources::Engine::ActsAsArchived (NameError)
```

I have not figured out what the issue is 🤔  Both gems work nicely on Rails 6.

**Comment by vikas-wadhwa-extendmed** [comment]
> effective_datatables and effective_resources, a dependency, are both working on Rails 7 now!

@matt-riemer is this a change that was made to the 3.x version as well? Is there a commit we can reference for local branches?

We are upgrading from rails 5.2.4 to rails 7 and near the finish line here but we're having this error on running rails console:

```
.gem/ruby/2.7.6/bundler/gems/effective_datatables-6f3e0fca2c6a/lib/effective_datatables/engine.rb:10:in `block (2 levels) in <class:Engine>': uninitialized constant EffectiveDatatables::Engine::EffectiveDatatablesHelper (NameError)
```

**Comment by matt-riemer** [comment]
Pretty sure the problem is the engine initializer.

The syntax kind of changed between rails versions. Gotta use that `app.config.to_prepare` block in newer apps instead of the old `ActiveSupport.on_load`

https://github.com/code-and-effect/effective_datatables/blob/master/lib/effective_datatables/engine.rb

Just copy & pasting the current master version of this engine.rb over the 3.0.x branch might work and be all the changes required for rails 7!  Might be another gotcha or two.
